# Keep this file minimal; zsh reads it for every shell.

typeset -U path PATH

path_prepend() {
  [[ -d "$1" ]] && path=("$1" $path)
}

path_prepend "$HOME/.local/bin"
path_prepend "$HOME/bin"
path_prepend "/opt/homebrew/bin"
path_prepend "/opt/homebrew/sbin"
path_prepend "/usr/local/bin"
path_prepend "/usr/local/sbin"
path_prepend "/home/linuxbrew/.linuxbrew/bin"
path_prepend "/home/linuxbrew/.linuxbrew/sbin"

export PATH
export EDITOR="nvim"
export VISUAL="nvim"
export PAGER="less"
